name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Runs `toLower` method
        uses: ./
        id: toLower
        with:
          method: 'toLower'
          value: 'HEllo tHeRE'

      - name: Assert output of `toLower`
        run: |
          if [ "${{ steps.toLower.outputs.value }}" != "hello there" ]; then exit 1; fi

      - name: Runs `camelCase` method
        uses: ./
        id: camelCase
        with:
          method: 'camelCase'
          value: 'Ahh, Hello There!'

      - name: Assert output of `camelCase`
        run: |
          if [ "${{ steps.camelCase.outputs.value }}" != "ahhHelloThere" ]; then exit 1; fi